# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8860f1132590652a01e9084784152731f95d767dbd7b035198eb653acdfd11f2e357be087e3dd3cf3834b45b776a258999340f3bbdc1a2b53fe71940e12cc4c7

test:
  secret_key_base: d7196d21e169ba3c96b5e80b8e5dc9b993b48b017afa29f5d0dbedc2c7751ccbe32b244090f25ac2d034565ba9fa1c8f02cc9fea4bc18f8efe9930c7430aca1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
